### ISSUE TITLE
Enable non-english charactar support (for example Cyrillic) in notifications

### ISSUE THREAD

**Issue by petRUShka** [abranson/rockpool#26] opened 2016-03-30 13:41 UTC
Since 3.9 release it is possible to enable non-English characters including Cyrillic via official Android and iOS apps:

> Cyrillic characters are now supported in notifications and alerts. Enable from the Pebble Time smartphone app: Menu » Settings » Watch Language » Selected Language.

proof: https://forums.getpebble.com/discussion/31068/pebble-firmware-3-9-released-2-3-2016-and-now-3-9-1

But if you have only Jolla smartphone and rockpool app it is impossible to use pebble due to lack of cyrillic characters.

Photo with example:

![squares instead of Cyrillic characters](https://habrastorage.org/storage2/3ef/45d/f0b/3ef45df0b0efd82eabdc416cc2f5998a.png)

**Comment by abranson** [comment] 2016-03-30 13:50
Thanks for this. I wonder if it's related to the pbl functionality.

**Comment by petRUShka** [comment] 2016-03-30 13:53
I'm not sure, but my guess is "no" or at least "not directly".

P.S. But it is possible that above mentioned option force Pebble Time app to upload corresponding `pbl` file.

**Comment by abranson** [comment] 2016-03-30 14:07
I think that might be exactly what that does.

**Comment by rufferson** [comment] 2016-04-07 19:10
![20160407210611](https://cloud.githubusercontent.com/assets/1273136/14363505/ec1b678e-fd04-11e5-9122-eceaa76abea7.jpg)
For me it actually works fine, I suspect only older pebbles require certain localization files. Or could it be encoding problem? (reminds me old koi8 days)

**Comment by abranson** [comment] 2016-04-16 08:29
Yes, this is the case - older Pebbles need the language files to supply their character sets, so implementing that should fix this. I'll close this as a dupe of #23.

**Closed by abranson** 2016-04-16 08:29 UTC
